bye321 = ["bye","goodbye"]
hay = ["I'm doing well, thank you.",
    "I'm great, how about you?",
    "Feeling good, thanks!",
    "I'm fine, and you?",
    "Not too bad, how about yourself?",
    "Doing fantastic!",
    "Pretty good, thanks for asking.",
    "I'm okay, just busy.",
    "Could be better, but I'm hanging in there.",
    "I'm excellent, thank you for asking.",
    "Feeling wonderful!",
    "Not too shabby!",
    "I'm doing fine, how about you?",
    "I'm on top of the world!",
    "Doing great, living the dream.",
    "I'm good, thanks for checking in.",
    "Feeling fantastic!",
    "I'm alright, and you?",
    "Not bad at all!",
    "I'm doing well, how are you doing?"]